<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Olivia Flowers</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <style>
    /* Стили для заголовка */
    .navbar-brand {
      font-size: 2rem; /* Размер шрифта */
    }
  </style>
</head>
<body>
<#include "blocks/header.ftlh">
</body>
</html>
