<ul class="nav navbar-custom nav-fill">
    <li class="nav-item my-3">
        <span class="nav-text disabled">Самара</span>
    </li>
    <li class="nav-item my-3">
        <span class="nav-text disabled">+7 999 999 99 99</span>
    </li>
    <li class="nav-item my-3">
        <span class="nav-text disabled">Вк</span>
    </li>
    <li class="nav-item my-3">
        <span class="nav-text disabled">Instagram</span>
    </li>
</ul>
